--[[

************************************************************************

deDE.lua

deDE localization strings for Collectinator

File date: @file-date-iso@ 
Project version: @project-version@

Please update:
http://www.wowace.com/projects/collectinator/localization/deDE/
for any translation additions or changes.

All credits for the translations belong to the individuals listed here:
http://www.wowace.com/projects/collectinator/localization/translators/

The translations will be auto-generated by the localization application.

************************************************************************

Please see http://www.wowace.com/projects/arl/for more information.

License:
	Please see LICENSE.txt

These translations are released under the Public Domain.

************************************************************************
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Collectinator", "deDE", false)

if not L then return end

--@localization(locale="deDE", format="lua_additive_table", handle-unlocalized="ignore", escape-non-ascii=false, same-key-is-true=true)@